#!/usr/bin/expect -f
#
# usage: expect -f func uploadfile remotepss remoteip remotedir remoteuser
#
# Author: Alex
################################

set timeout 30
set hiveresult [lindex $argv 0]
set drowssap [lindex $argv 1]
set remotehost [lindex $argv 2]
set destdir [lindex $argv 3]
set username [lindex $argv 4]

spawn scp $hiveresult $username@$remotehost:$destdir
expect {
-re ".*es.*n.*" {
exp_send "yes\r"
exp_continue
}
-re ".*word.*" {
exp_send "$drowssap\r"
}
}
expect eof

